### ISSUE TITLE
Feature: Player shooting based on crosshair

### ISSUE THREAD

**Issue by jyee27** [mischano/Unity#1]
Do This
---
* Add a crosshair to the camera
* Add a camera follow point to the player, either over the shoulder or above
* In `PlayerShoot.cs`, draw a raycast from the crosshair to the world to determine direction to shoot and shoot in that direction
  * May need special handling if we're not aiming at anything e.g. into space
* In `PlayerMovement.cs`, quickly lerp player's rotation to where we're aiming at
  * This may look better if we have an "aiming state" for this type of rotation that lasts for a few seconds after shooting, like Risk of Rain 2.
  * Make sure the projectile doesn't instantly hit the player.

**Comment by mischano** [comment]
@ashmayer

**Comment by jyee27** [comment]
Done: #7 
We don't change the player's rotation but in the future we could add an animation.
