### ISSUE TITLE
Feature: Enemy health bars

### ISSUE THREAD

**Issue by jyee27** [mischano/Unity#3]
* Add a `[SerializeField] UnityEvent _onHealthChanged` to `Health.cs`
* Add a health bar slider to the Alien prefab
* Add a `HealthBar.cs` script to the health slider
  * Should have a `public void ChangeHealth()` function that lerps the health bar to the right amount
    * See notes from class, but also make sure to stop the previous coroutine before starting another.
    * Call this function from the `_onHealthChanged` UnityEvent in `Health.cs`. Set it in the editor using `[SerializeField]`.
  * Slider should face the player's camera. Use `Camera.main` to get the main camera
  * (Optional) Slider should fade out or hide after health stops changing for a few seconds

**Comment by mischano** [comment]
Closing this because it has it has been implemented yesterday in backup scene.

**Comment by jyee27** [comment]
https://github.com/mischano/Unity/commit/f92efb2d95c6fd733141382912b06c368feab658
Health bar is now functional. Making the slider fade out over time is still TODO.

**Comment by jyee27** [comment]
https://github.com/mischano/Unity/commit/2c34540ef158bf4151a521fb553617d9f68aa621
Slider now fades out
