### ISSUE TITLE
Feature: Shield generator

### ISSUE THREAD

**Issue by jyee27** [mischano/Unity#4]
Create a Shield Generator prefab.
* Use a cube as a temp model
* Give it the `Health.cs` and `ShieldGenerator.cs` scripts
* Update the `ShieldGenerator.cs` script
  * Give it a `[SerializeField] GameObject _shield` variable
  * In `OnDeath()`, destroy the `_shield`, maybe after a short delay
  * Also add a `[SerializeField] UnityEvent _onDeath` that we invoke on death so we can attach events e.g. spawning aliens later
* Make this a prefab and attach a shield object in the prefab for convenience
* Add effects if you have time

**Comment by mischano** [comment]
@Kytoshi

**Comment by vohnjogel** [comment]
Completed with placeholder textures
