### ISSUE TITLE
Shield generator polish

### ISSUE THREAD

**Issue by jyee27** [mischano/Unity#9]
We want to better communicate to the player how the shield generator works and what it does.
- Add some detail to the box 
- Add a glowing? wire between the box and the shield
- Adjust shield effects/material to make it look nice
- Remove health bar
- Add particle effect to the box when it takes damage to highlight that it can take damage and be destroyed
- Make the shield attachable to NPC's such as shooting turret instead of a box for later levels.

**Comment by mischano** [comment]
Maybe remove the health bar from the box and explosion effect to box when it gets destroyed.

**Comment by jyee27** [comment]
We can remove the health bar, but we should probably add some indicator of damage. The flashing red on damage effect I described in #8 would be good.

**Comment by mischano** [comment]
Yes, definitely. Whenever the box takes damage, we can add red glowing effect or some other particle effects.

**Comment by vohnjogel** [comment]
I'm happy to pick up this issue, I've been doing some work on shield effects using the tutorial someone posted on discord

**Comment by jyee27** [comment]
Idea: give the shield generator a gun and make it a turret

**Comment by jyee27** [comment]
Idea: laser targets, buttons that activate force field platforms on a timer
